// Define a type for the local government area
export type LocalGovernmentArea = {
  name: string;
  abbreviation: string;
};

// Define a type for the states and their local government areas
export type StateLocalGovernments = {
  [state: string]: LocalGovernmentArea[];
};

export const localGovernments: StateLocalGovernments = {
  Abia: [
    { name: "Aba North", abbreviation: "ABN" },
    { name: "Aba South", abbreviation: "ABS" },
    { name: "Arochukwu", abbreviation: "ARO" },
    { name: "Bende", abbreviation: "BEN" },
    { name: "Ikwuano", abbreviation: "IKW" },
    { name: "Isiala Ngwa North", abbreviation: "ISN" },
    { name: "Isiala Ngwa South", abbreviation: "ISS" },
    { name: "Isukwuato", abbreviation: "ISU" },
    { name: "Obingwa", abbreviation: "OBI" },
    { name: "Ohafia", abbreviation: "OHA" },
    { name: "Osisioma", abbreviation: "OSI" },
    { name: "Ugwunagbo", abbreviation: "UGW" },
    { name: "Ukwa East", abbreviation: "UKE" },
    { name: "Ukwa West", abbreviation: "UKW" },
    { name: "Umuahia North", abbreviation: "UMN" },
    { name: "Umuahia South", abbreviation: "UMS" },
    { name: "Umu Nne", abbreviation: "UMN" },
  ],
  Adamawa: [
    { name: "Demsa", abbreviation: "DEM" },
    { name: "Fufore", abbreviation: "FUF" },
    { name: "Ganye", abbreviation: "GAN" },
    { name: "Girei", abbreviation: "GIR" },
    { name: "Gombi", abbreviation: "GOM" },
    { name: "Guyuk", abbreviation: "GUY" },
    { name: "Hong", abbreviation: "HON" },
    { name: "Jada", abbreviation: "JAD" },
    { name: "Lamurde", abbreviation: "LAM" },
    { name: "Madagali", abbreviation: "MAD" },
    { name: "Maiha", abbreviation: "MAI" },
    { name: "Mayo-Belwa", abbreviation: "MAY" },
    { name: "Michika", abbreviation: "MIC" },
    { name: "Mubi North", abbreviation: "MUB" },
    { name: "Mubi South", abbreviation: "MUS" },
    { name: "Numan", abbreviation: "NUM" },
    { name: "Shelleng", abbreviation: "SHE" },
    { name: "Song", abbreviation: "SON" },
    { name: "Yola North", abbreviation: "YON" },
    { name: "Yola South", abbreviation: "YOS" },
  ],
  AkwaIbom: [
    { name: "Abak", abbreviation: "ABA" },
    { name: "Eket", abbreviation: "EKE" },
    { name: "Esit Eket", abbreviation: "ESE" },
    { name: "Essien Udim", abbreviation: "ESS" },
    { name: "Etim Ekpo", abbreviation: "ETI" },
    { name: "Etinan", abbreviation: "ETI" },
    { name: "Ibeno", abbreviation: "IBE" },
    { name: "Ibesikpo Asutan", abbreviation: "IBE" },
    { name: "Ikot Abasi", abbreviation: "IKA" },
    { name: "Ikot Ekpene", abbreviation: "IKE" },
    { name: "Ibiono Ibom", abbreviation: "IBI" },
    { name: "Ikono", abbreviation: "IKN" },
    { name: "Ini", abbreviation: "INI" },
    { name: "Itu", abbreviation: "ITU" },
    { name: "Mbo", abbreviation: "MBO" },
    { name: "Mkpat Enin", abbreviation: "MKE" },
    { name: "Nsit Atai", abbreviation: "NAT" },
    { name: "Nsit Ibom", abbreviation: "NSI" },
    { name: "Nsit Ubium", abbreviation: "NSU" },
    { name: "Obot Akara", abbreviation: "OBO" },
    { name: "Okobo", abbreviation: "OKO" },
    { name: "Oruk Anam", abbreviation: "ORU" },
    { name: "Uruan", abbreviation: "URU" },
    { name: "Urue Offong/Oruko", abbreviation: "URF" },
    { name: "Uyo", abbreviation: "UYO" },
  ],
  Anambra: [
    { name: "Aguata", abbreviation: "AGU" },
    { name: "Awka North", abbreviation: "AWK" },
    { name: "Awka South", abbreviation: "AWS" },
    { name: "Anambra East", abbreviation: "ANE" },
    { name: "Anambra West", abbreviation: "ANW" },
    { name: "Ayamelum", abbreviation: "AYA" },
    { name: "Dunukofia", abbreviation: "DUN" },
    { name: "Ekwusigo", abbreviation: "EKW" },
    { name: "Idemili North", abbreviation: "IDN" },
    { name: "Idemili South", abbreviation: "IDS" },
    { name: "Ihiala", abbreviation: "IHI" },
    { name: "Njikoka", abbreviation: "NJI" },
    { name: "Nnewi North", abbreviation: "NNN" },
    { name: "Nnewi South", abbreviation: "NNS" },
    { name: "Ogbaru", abbreviation: "OGB" },
    { name: "Onitsha North", abbreviation: "ONN" },
    { name: "Onitsha South", abbreviation: "ONS" },
    { name: "Orumba North", abbreviation: "ORN" },
    { name: "Orumba South", abbreviation: "ORS" },
    { name: "Oyi", abbreviation: "OYI" },
  ],
  Bauchi: [
    { name: "Bauchi", abbreviation: "BAU" },
    { name: "Bogoro", abbreviation: "BOG" },
    { name: "Damban", abbreviation: "DAM" },
    { name: "Dass", abbreviation: "DAS" },
    { name: "Gamawa", abbreviation: "GAM" },
    { name: "Ganjuwa", abbreviation: "GJW" },
    { name: "Giade", abbreviation: "GIA" },
    { name: "Itas/Gadau", abbreviation: "ITA" },
    { name: "Jama'are", abbreviation: "JAM" },
    { name: "Katagum", abbreviation: "KAT" },
    { name: "Kirfi", abbreviation: "KIR" },
    { name: "Misau", abbreviation: "MIS" },
    { name: "Ningi", abbreviation: "NIN" },
    { name: "Shira", abbreviation: "SHI" },
    { name: "Tafawa Balewa", abbreviation: "TAF" },
    { name: "Toro", abbreviation: "TOR" },
    { name: "Warji", abbreviation: "WAR" },
    { name: "Zaki", abbreviation: "ZAK" },
  ],
  Bayelsa: [
    { name: "Brass", abbreviation: "BRA" },
    { name: "Ekeremor", abbreviation: "EKE" },
    { name: "Nembe", abbreviation: "NEM" },
    { name: "Ogbia", abbreviation: "OGB" },
    { name: "Sagbama", abbreviation: "SAG" },
    { name: "Southern Ijaw", abbreviation: "SOI" },
    { name: "Yenagoa", abbreviation: "YEN" },
  ],
  Benue: [
    { name: "Ado", abbreviation: "ADO" },
    { name: "Gboko", abbreviation: "GBK" },
    { name: "Makurdi", abbreviation: "MAK" },
    { name: "Ogbadibo", abbreviation: "OGB" },
    { name: "Oju", abbreviation: "OJU" },
    { name: "Okpokwu", abbreviation: "OKP" },
    { name: "Oturkpo", abbreviation: "OTU" },
    { name: "Tarka", abbreviation: "TAR" },
    { name: "Ukum", abbreviation: "UKU" },
    { name: "Ushongo", abbreviation: "USH" },
  ],
  Borno: [
    { name: "Abadam", abbreviation: "ABA" },
    { name: "Askira/Uba", abbreviation: "ASK" },
    { name: "Bama", abbreviation: "BAM" },
    { name: "Bayo", abbreviation: "BAY" },
    { name: "Biu", abbreviation: "BIU" },
    { name: "Chibok", abbreviation: "CHI" },
    { name: "Damboa", abbreviation: "DAM" },
    { name: "Dikwa", abbreviation: "DIK" },
    { name: "Gubio", abbreviation: "GUB" },
    { name: "Gwoza", abbreviation: "GWO" },
    { name: "Jere", abbreviation: "JER" },
    { name: "Kaga", abbreviation: "KAG" },
    { name: "Kala/Balge", abbreviation: "KAL" },
    { name: "Konduga", abbreviation: "KON" },
    { name: "Kukawa", abbreviation: "KUK" },
    { name: "Kwaya Kusar", abbreviation: "KWK" },
    { name: "Maiduguri", abbreviation: "MAI" },
    { name: "Monguno", abbreviation: "MON" },
    { name: "Ngala", abbreviation: "NGA" },
    { name: "Nganzai", abbreviation: "NGA" },
    { name: "Shani", abbreviation: "SHA" },
  ],
  CrossRiver: [
    { name: "Akamkpa", abbreviation: "AKM" },
    { name: "Akpabuyo", abbreviation: "AKP" },
    { name: "Bekwarra", abbreviation: "BEK" },
    { name: "Biase", abbreviation: "BIA" },
    { name: "Boki", abbreviation: "BOK" },
    { name: "Calabar Municipality", abbreviation: "CAL" },
    { name: "Calabar South", abbreviation: "CAS" },
    { name: "Etung", abbreviation: "ETU" },
    { name: "Ikom", abbreviation: "IKM" },
    { name: "Obanliku", abbreviation: "OBA" },
    { name: "Obubra", abbreviation: "OBU" },
    { name: "Obudu", abbreviation: "OBU" },
    { name: "Odukpani", abbreviation: "ODU" },
    { name: "Ogoja", abbreviation: "OGO" },
    { name: "Yala", abbreviation: "YAL" },
  ],
  Delta: [
    { name: "Aniocha North", abbreviation: "ANI" },
    { name: "Aniocha South", abbreviation: "ANS" },
    { name: "Bomadi", abbreviation: "BOM" },
    { name: "Burutu", abbreviation: "BUR" },
    { name: "Isoko North", abbreviation: "ISN" },
    { name: "Isoko South", abbreviation: "ISS" },
    { name: "Ika North East", abbreviation: "IKA" },
    { name: "Ika South", abbreviation: "IKS" },
    { name: "Ilaje", abbreviation: "ILA" },
    { name: "Ndokwa East", abbreviation: "NDK" },
    { name: "Ndokwa West", abbreviation: "NDW" },
    { name: "Okpe", abbreviation: "OKP" },
    { name: "Oshimili North", abbreviation: "OSH" },
    { name: "Oshimili South", abbreviation: "OSS" },
    { name: "Patani", abbreviation: "PAT" },
    { name: "Sapele", abbreviation: "SAP" },
    { name: "Udu", abbreviation: "UDU" },
    { name: "Ukwuani", abbreviation: "UKW" },
    { name: "Uvwie", abbreviation: "UVW" },
    { name: "Warri North", abbreviation: "WAR" },
    { name: "Warri South", abbreviation: "WAS" },
    { name: "Warri South West", abbreviation: "WSW" },
  ],
  Ebonyi: [
    { name: "Abakaliki", abbreviation: "ABA" },
    { name: "Afikpo North", abbreviation: "AFI" },
    { name: "Afikpo South", abbreviation: "AFS" },
    { name: "Ebonyi", abbreviation: "EBO" },
    { name: "Ezza North", abbreviation: "EZN" },
    { name: "Ezza South", abbreviation: "EZB" },
    { name: "Ikwo", abbreviation: "IKW" },
    { name: "Ishielu", abbreviation: "ISH" },
    { name: "Ivo", abbreviation: "IVO" },
    { name: "Ohaozara", abbreviation: "OHA" },
    { name: "Onicha", abbreviation: "ONI" },
  ],
  Edo: [
    { name: "Akoko-Edo", abbreviation: "AKE" },
    { name: "Egor", abbreviation: "EGO" },
    { name: "Esan Central", abbreviation: "ESC" },
    { name: "Esan North East", abbreviation: "ENE" },
    { name: "Esan South East", abbreviation: "ESE" },
    { name: "Esan West", abbreviation: "ESW" },
    { name: "Etsako Central", abbreviation: "ETC" },
    { name: "Etsako East", abbreviation: "ETE" },
    { name: "Etsako West", abbreviation: "ETW" },
    { name: "Igueben", abbreviation: "IGU" },
    { name: "Ikpoba-Okha", abbreviation: "IKP" },
    { name: "Oredo", abbreviation: "ORE" },
    { name: "Orhionmwon", abbreviation: "ORH" },
    { name: "Ovia North East", abbreviation: "OVN" },
    { name: "Ovia South West", abbreviation: "OVS" },
    { name: "Uhunmwonde", abbreviation: "UHU" },
  ],
  Ekiti: [
    { name: "Ado Ekiti", abbreviation: "ADO" },
    { name: "Ekiti East", abbreviation: "EKE" },
    { name: "Ekiti South West", abbreviation: "ESW" },
    { name: "Ekiti West", abbreviation: "EKW" },
    { name: "Emure", abbreviation: "EMU" },
    { name: "Efon", abbreviation: "EFN" },
    { name: "Ilejemeje", abbreviation: "ILE" },
    { name: "Irepodun/Ifelodun", abbreviation: "IRI" },
    { name: "Ise/Orun", abbreviation: "ISE" },
    { name: "Moba", abbreviation: "MOB" },
    { name: "Oye", abbreviation: "OYE" },
  ],
  Enugu: [
    { name: "Enugu East", abbreviation: "ENE" },
    { name: "Enugu North", abbreviation: "ENN" },
    { name: "Enugu South", abbreviation: "ENS" },
    { name: "Ezeagu", abbreviation: "EZE" },
    { name: "Igbo Etiti", abbreviation: "IGE" },
    { name: "Igbo Eze North", abbreviation: "IEN" },
    { name: "Igbo Eze South", abbreviation: "IES" },
    { name: "Isi Uzo", abbreviation: "ISU" },
    { name: "Nkanu East", abbreviation: "NKE" },
    { name: "Nkanu West", abbreviation: "NKW" },
    { name: "Oji River", abbreviation: "OJI" },
    { name: "Udenu", abbreviation: "UDE" },
    { name: "Udi", abbreviation: "UDI" },
    { name: "Uzo Uwani", abbreviation: "UZU" },
  ],
  Imo: [
    { name: "Aboh Mbaise", abbreviation: "ABO" },
    { name: "Ahiazu Mbaise", abbreviation: "AHM" },
    { name: "Ahiazu Mbaise", abbreviation: "AHA" },
    { name: "Ezinihitte", abbreviation: "EZI" },
    { name: "Ideato North", abbreviation: "IDE" },
    { name: "Ideato South", abbreviation: "IDS" },
    { name: "Ihitte/Uboma", abbreviation: "IHU" },
    { name: "Ikeduru", abbreviation: "IKE" },
    { name: "Ikeduru", abbreviation: "IKR" },
    { name: "Isiala Mbano", abbreviation: "ISL" },
    { name: "Isu", abbreviation: "ISU" },
    { name: "Mbaitoli", abbreviation: "MBA" },
    { name: "Ngor Okpala", abbreviation: "NGO" },
    { name: "Njaba", abbreviation: "NJA" },
    { name: "Nwangele", abbreviation: "NWA" },
    { name: "Nwangele", abbreviation: "NWG" },
    { name: "Obowo", abbreviation: "OBW" },
    { name: "Oguta", abbreviation: "OGU" },
    { name: "Ohaji/Egbema", abbreviation: "OHA" },
    { name: "Okigwe", abbreviation: "OKI" },
    { name: "Orlu", abbreviation: "ORL" },
    { name: "Orsu", abbreviation: "ORS" },
    { name: "Owerri North", abbreviation: "OWN" },
    { name: "Owerri West", abbreviation: "OWW" },
    { name: "Owerri South", abbreviation: "OWS" },
  ],
  Jigawa: [
    { name: "Auyo", abbreviation: "AUY" },
    { name: "Babura", abbreviation: "BAB" },
    { name: "Biriniwa", abbreviation: "BIR" },
    { name: "Birnin Kudu", abbreviation: "BIR" },
    { name: "Dutse", abbreviation: "DUT" },
    { name: "Gagarawa", abbreviation: "GAG" },
    { name: "Garki", abbreviation: "GAR" },
    { name: "Gumel", abbreviation: "GUM" },
    { name: "Guri", abbreviation: "GUR" },
    { name: "Gwaram", abbreviation: "GWA" },
    { name: "Gwiwa", abbreviation: "GWI" },
    { name: "Hadejia", abbreviation: "HAD" },
    { name: "Jahun", abbreviation: "JAH" },
    { name: "Kafin Hausa", abbreviation: "KAF" },
    { name: "Kaugama", abbreviation: "KAU" },
    { name: "Kazaure", abbreviation: "KAZ" },
    { name: "Kiri Kasama", abbreviation: "KIR" },
    { name: "Kiyawa", abbreviation: "KIY" },
    { name: "Maigatari", abbreviation: "MAI" },
    { name: "Malam Madori", abbreviation: "MAL" },
    { name: "Miga", abbreviation: "MIG" },
    { name: "Ringim", abbreviation: "RIN" },
    { name: "Roni", abbreviation: "RON" },
    { name: "Sule Tankarkar", abbreviation: "SUL" },
    { name: "Tarka", abbreviation: "TAR" },
    { name: "Taura", abbreviation: "TAU" },
    { name: "Zaki", abbreviation: "ZAK" },
  ],
  Kaduna: [
    { name: "Birnin Gwari", abbreviation: "BGW" },
    { name: "Chikun", abbreviation: "CHI" },
    { name: "Giwa", abbreviation: "GIW" },
    { name: "Igabi", abbreviation: "IGA" },
    { name: "Ikara", abbreviation: "IKA" },
    { name: "Jaba", abbreviation: "JAB" },
    { name: "Jema'a", abbreviation: "JEM" },
    { name: "Kachia", abbreviation: "KAC" },
    { name: "Kaduna North", abbreviation: "KDN" },
    { name: "Kaduna South", abbreviation: "KDS" },
    { name: "Kagarko", abbreviation: "KAG" },
    { name: "Kajuru", abbreviation: "KAJ" },
    { name: "Kano", abbreviation: "KAN" },
    { name: "Kauru", abbreviation: "KAU" },
    { name: "Kubau", abbreviation: "KUB" },
    { name: "Kudan", abbreviation: "KUD" },
    { name: "Lere", abbreviation: "LER" },
    { name: "Makarfi", abbreviation: "MAK" },
    { name: "Sabon Gari", abbreviation: "SAB" },
    { name: "Sanga", abbreviation: "SAN" },
    { name: "Soba", abbreviation: "SOB" },
    { name: "Zangon Kataf", abbreviation: "ZAN" },
    { name: "Zaria", abbreviation: "ZAR" },
  ],
  Kano: [
    { name: "Ajingi", abbreviation: "AJI" },
    { name: "Albasu", abbreviation: "ALB" },
    { name: "Bagwai", abbreviation: "BAG" },
    { name: "Bebeji", abbreviation: "BEB" },
    { name: "Bichi", abbreviation: "BIC" },
    { name: "Bunkure", abbreviation: "BUN" },
    { name: "Dala", abbreviation: "DAL" },
    { name: "Dambatta", abbreviation: "DAM" },
    { name: "Dawakin Kudu", abbreviation: "DAK" },
    { name: "Dawakin Tofa", abbreviation: "DAT" },
    { name: "Doguwa", abbreviation: "DOG" },
    { name: "Fagge", abbreviation: "FAG" },
    { name: "Gabasawa", abbreviation: "GAB" },
    { name: "Garko", abbreviation: "GAR" },
    { name: "Garun Malam", abbreviation: "GAM" },
    { name: "Gaya", abbreviation: "GAY" },
    { name: "Gezawa", abbreviation: "GEZ" },
    { name: "Gwale", abbreviation: "GWA" },
    { name: "Kano Municipal", abbreviation: "KAN" },
    { name: "Karaye", abbreviation: "KAR" },
    { name: "Kibiya", abbreviation: "KIB" },
    { name: "Kiru", abbreviation: "KIR" },
    { name: "Kumbotso", abbreviation: "KUM" },
    { name: "Kunchi", abbreviation: "KUN" },
    { name: "Kura", abbreviation: "KUR" },
    { name: "Madobi", abbreviation: "MAD" },
    { name: "Makoda", abbreviation: "MAK" },
    { name: "Minjibir", abbreviation: "MIN" },
    { name: "Nasarawa", abbreviation: "NAS" },
    { name: "Rimin Gado", abbreviation: "RIM" },
    { name: "Rogo", abbreviation: "ROG" },
    { name: "Tarauni", abbreviation: "TAR" },
    { name: "Tofa", abbreviation: "TOF" },
    { name: "Tsanyawa", abbreviation: "TSA" },
    { name: "Wudil", abbreviation: "WUD" },
  ],
  Katsina: [
    { name: "Bakori", abbreviation: "BAK" },
    { name: "Batagarawa", abbreviation: "BAT" },
    { name: "Batsari", abbreviation: "BAT" },
    { name: "Baure", abbreviation: "BAU" },
    { name: "Bingi", abbreviation: "BIN" },
    { name: "Charanchi", abbreviation: "CHA" },
    { name: "Dutsi", abbreviation: "DUT" },
    { name: "Dutsinma", abbreviation: "DUT" },
    { name: "Funtua", abbreviation: "FUN" },
    { name: "Jibia", abbreviation: "JIB" },
    { name: "Kaita", abbreviation: "KAI" },
    { name: "Kankara", abbreviation: "KAN" },
    { name: "Kankia", abbreviation: "KAN" },
    { name: "Katsina", abbreviation: "KAT" },
    { name: "Kurfi", abbreviation: "KUR" },
    { name: "Kusada", abbreviation: "KUS" },
    { name: "Mai'adua", abbreviation: "MAI" },
    { name: "Malumfashi", abbreviation: "MAL" },
    { name: "Mani", abbreviation: "MAN" },
    { name: "Mashi", abbreviation: "MAS" },
    { name: "Matazu", abbreviation: "MAT" },
    { name: "Musawa", abbreviation: "MUS" },
    { name: "Rimi", abbreviation: "RIM" },
    { name: "Sabuwa", abbreviation: "SAB" },
    { name: "Safana", abbreviation: "SAF" },
    { name: "Sandamu", abbreviation: "SAN" },
    { name: "Zango", abbreviation: "ZAN" },
  ],
  Kebbi: [
    { name: "Aleiro", abbreviation: "ALE" },
    { name: "Argungu", abbreviation: "ARG" },
    { name: "Augie", abbreviation: "AUG" },
    { name: "Bagudo", abbreviation: "BAG" },
    { name: "Birnin Kebbi", abbreviation: "BIR" },
    { name: "Dandi", abbreviation: "DAN" },
    { name: "Arewa", abbreviation: "ARE" },
    { name: "Gwandu", abbreviation: "GWA" },
    { name: "Jega", abbreviation: "JEG" },
    { name: "Koko/Besse", abbreviation: "KOK" },
    { name: "Maiyama", abbreviation: "MAI" },
    { name: "Ngaski", abbreviation: "NGA" },
    { name: "Sakaba", abbreviation: "SAK" },
    { name: "Shanga", abbreviation: "SHA" },
    { name: "Suru", abbreviation: "SUR" },
    { name: "Yauri", abbreviation: "YAU" },
    { name: "Zuru", abbreviation: "ZUR" },
  ],
  Kogi: [
    { name: "Adavi", abbreviation: "ADA" },
    { name: "Ajaokuta", abbreviation: "AJA" },
    { name: "Bassa", abbreviation: "BAS" },
    { name: "Dekina", abbreviation: "DEK" },
    { name: "Ibaji", abbreviation: "IBA" },
    { name: "Idah", abbreviation: "IDA" },
    { name: "Igalamela/Odolu", abbreviation: "IGA" },
    { name: "Kabba/Bunu", abbreviation: "KAB" },
    { name: "Kogi", abbreviation: "KOG" },
    { name: "Mopa Muro", abbreviation: "MOP" },
    { name: "Ogori/Magongo", abbreviation: "OGM" },
    { name: "Okehi", abbreviation: "OKE" },
    { name: "Okene", abbreviation: "OKE" },
    { name: "Olamaboro", abbreviation: "OLA" },
    { name: "Omala", abbreviation: "OMA" },
    { name: "Yagba East", abbreviation: "YAG" },
    { name: "Yagba West", abbreviation: "YAW" },
  ],
  Kwara: [
    { name: "Asa", abbreviation: "ASA" },
    { name: "Baruten", abbreviation: "BAR" },
    { name: "Ekiti", abbreviation: "EKI" },
    { name: "Ifelodun", abbreviation: "IFE" },
    { name: "Ilorin East", abbreviation: "ILE" },
    { name: "Ilorin South", abbreviation: "ILS" },
    { name: "Ilorin West", abbreviation: "ILW" },
    { name: "Isin", abbreviation: "ISI" },
    { name: "Irepodun", abbreviation: "IRE" },
    { name: "Offa", abbreviation: "OFF" },
    { name: "Oke Ero", abbreviation: "OKE" },
    { name: "Oyun", abbreviation: "OYU" },
    { name: "Pategi", abbreviation: "PAT" },
  ],
  Lagos: [
    { name: "Agege", abbreviation: "AGE" },
    { name: "Ajeromi-Ifelodun", abbreviation: "AJI" },
    { name: "Alimosho", abbreviation: "ALI" },
    { name: "Apapa", abbreviation: "APA" },
    { name: "Badagry", abbreviation: "BAD" },
    { name: "Epe", abbreviation: "EPE" },
    { name: "Ikeja", abbreviation: "IKE" },
    { name: "Ikorodu", abbreviation: "IKO" },
    { name: "Lagos Island", abbreviation: "LAG" },
    { name: "Lagos Mainland", abbreviation: "LAM" },
    { name: "Lagos South West", abbreviation: "LAS" },
    { name: "Lagos West", abbreviation: "LAK" },
    { name: "Surulere", abbreviation: "SUR" },
  ],
  Nasarawa: [
    { name: "Akwanga", abbreviation: "AKW" },
    { name: "Doma", abbreviation: "DOM" },
    { name: "Keffi", abbreviation: "KEF" },
    { name: "Kokona", abbreviation: "KOK" },
    { name: "Lafia", abbreviation: "LAF" },
    { name: "Nasarawa", abbreviation: "NAS" },
    { name: "Nasarawa Egon", abbreviation: "NAS" },
    { name: "Obi", abbreviation: "OBI" },
    { name: "Toto", abbreviation: "TOT" },
    { name: "Wamba", abbreviation: "WAM" },
  ],
  Niger: [
    { name: "Agwara", abbreviation: "AGW" },
    { name: "Bida", abbreviation: "BID" },
    { name: "Borgu", abbreviation: "BOR" },
    { name: "Chanchaga", abbreviation: "CHA" },
    { name: "Edati", abbreviation: "EDA" },
    { name: "Gbako", abbreviation: "GBA" },
    { name: "Gbagyi", abbreviation: "GBA" },
    { name: "Katcha", abbreviation: "KAT" },
    { name: "Kontagora", abbreviation: "KON" },
    { name: "Lavun", abbreviation: "LAV" },
    { name: "Magama", abbreviation: "MAG" },
    { name: "Mokwa", abbreviation: "MOK" },
    { name: "Rafi", abbreviation: "RAF" },
    { name: "Rijau", abbreviation: "RIJ" },
    { name: "Shiroro", abbreviation: "SHI" },
    { name: "Wushishi", abbreviation: "WUS" },
  ],
  Ogun: [
    { name: "Abeokuta North", abbreviation: "ABE" },
    { name: "Abeokuta South", abbreviation: "ABO" },
    { name: "Ado-Odo/Ota", abbreviation: "ADO" },
    { name: "Ewekoro", abbreviation: "EWE" },
    { name: "Ifo", abbreviation: "IFO" },
    { name: "Ijebu East", abbreviation: "IJE" },
    { name: "Ijebu North", abbreviation: "IJU" },
    { name: "Ijebu North East", abbreviation: "IJN" },
    { name: "Ijebu Ode", abbreviation: "IJO" },
    { name: "Ijebu South West", abbreviation: "IJS" },
    { name: "Ikenne", abbreviation: "IKE" },
    { name: "Imeko-Afon", abbreviation: "IME" },
    { name: "Obafemi Owode", abbreviation: "OBA" },
    { name: "Odeda", abbreviation: "ODE" },
    { name: "Odogbolu", abbreviation: "ODO" },
    { name: "Ogun Waterside", abbreviation: "OGW" },
    { name: "Remo North", abbreviation: "REM" },
    { name: "Remo South", abbreviation: "RES" },
    { name: "Yewa North", abbreviation: "YEW" },
    { name: "Yewa South", abbreviation: "YES" },
  ],
  Ondo: [
    { name: "Akure North", abbreviation: "AKN" },
    { name: "Akure South", abbreviation: "AKS" },
    { name: "Ese Odo", abbreviation: "ESO" },
    { name: "Idanre", abbreviation: "IDA" },
    { name: "Ifedore", abbreviation: "IFE" },
    { name: "Ilaje", abbreviation: "ILA" },
    { name: "Odigbo", abbreviation: "ODI" },
    { name: "Okitipupa", abbreviation: "OKI" },
    { name: "Ondo East", abbreviation: "OND" },
    { name: "Ondo West", abbreviation: "ONW" },
    { name: "Ose", abbreviation: "OSE" },
    { name: "Owo", abbreviation: "OWO" },
  ],
  Osun: [
    { name: "Atakumosa East", abbreviation: "ATE" },
    { name: "Atakumosa West", abbreviation: "ATW" },
    { name: "Boluwaduro", abbreviation: "BOL" },
    { name: "Boluwaduro", abbreviation: "BOW" },
    { name: "Egbedore", abbreviation: "EGD" },
    { name: "Ejigbo", abbreviation: "EJI" },
    { name: "Ifelodun", abbreviation: "IFE" },
    { name: "Ife Central", abbreviation: "IFC" },
    { name: "Ife East", abbreviation: "IFE" },
    { name: "Ife North", abbreviation: "IFN" },
    { name: "Ife South", abbreviation: "IFS" },
    { name: "Ilesa East", abbreviation: "ILE" },
    { name: "Ilesa West", abbreviation: "ILW" },
    { name: "Irepodun", abbreviation: "IRE" },
    { name: "Iwo", abbreviation: "IWO" },
    { name: "Obokun", abbreviation: "OBO" },
    { name: "Orolu", abbreviation: "ORO" },
    { name: "Osogbo", abbreviation: "OSO" },
  ],
  Oyo: [
    { name: "Akinyele", abbreviation: "AKI" },
    { name: "Atiba", abbreviation: "ATI" },
    { name: "Atisbo", abbreviation: "ATI" },
    { name: "Egbeda", abbreviation: "EGB" },
    { name: "Ibadan North", abbreviation: "IBN" },
    { name: "Ibadan North East", abbreviation: "INE" },
    { name: "Ibadan North West", abbreviation: "INW" },
    { name: "Ibadan South East", abbreviation: "ISE" },
    { name: "Ibadan South West", abbreviation: "ISW" },
    { name: "Ibarapa Central", abbreviation: "IBC" },
    { name: "Ibarapa East", abbreviation: "IBE" },
    { name: "Ibarapa North", abbreviation: "IBN" },
    { name: "Itesiwaju", abbreviation: "ITE" },
    { name: "Kajola", abbreviation: "KAJ" },
    { name: "Lagelu", abbreviation: "LAG" },
    { name: "Ogbomoso North", abbreviation: "OGB" },
    { name: "Ogbomoso South", abbreviation: "OGS" },
    { name: "Oyo East", abbreviation: "OYE" },
    { name: "Oyo West", abbreviation: "OYW" },
  ],
  Plateau: [
    { name: "Barkin Ladi", abbreviation: "BAR" },
    { name: "Bassa", abbreviation: "BAS" },
    { name: "Jos East", abbreviation: "JOS" },
    { name: "Jos North", abbreviation: "JON" },
    { name: "Jos South", abbreviation: "JOS" },
    { name: "Kanke", abbreviation: "KAN" },
    { name: "Langtang North", abbreviation: "LAN" },
    { name: "Langtang South", abbreviation: "LAS" },
    { name: "Mangu", abbreviation: "MAN" },
    { name: "Pankshin", abbreviation: "PAN" },
    { name: "Qua'an Pan", abbreviation: "QAP" },
    { name: "Riyom", abbreviation: "RIY" },
    { name: "Wase", abbreviation: "WAS" },
  ],
  Rivers: [
    { name: "Port Harcourt", abbreviation: "PHC" },
    { name: "Obio/Akpor", abbreviation: "OBA" },
    { name: "Ikwerre", abbreviation: "IKW" },
    { name: "Etche", abbreviation: "ETC" },
    { name: "Emohua", abbreviation: "EMO" },
    { name: "Okrika", abbreviation: "OKR" },
    { name: "Ogu/Bolo", abbreviation: "OGU" },
    { name: "Khana", abbreviation: "KHA" },
    { name: "Gokana", abbreviation: "GOK" },
    { name: "Eleme", abbreviation: "ELE" },
    { name: "Ogba/Egbema/Ndoni", abbreviation: "OGE" },
    { name: "Ahoada East", abbreviation: "AHO" },
    { name: "Ahoada West", abbreviation: "AHW" },
    { name: "Degema", abbreviation: "DEG" },
    { name: "Asari-Toru", abbreviation: "ASR" },
  ],
  Sokoto: [
    { name: "Binji", abbreviation: "BIN" },
    { name: "Bodinga", abbreviation: "BOD" },
    { name: "Dange Shuni", abbreviation: "DAN" },
    { name: "Gada", abbreviation: "GAD" },
    { name: "Goronyo", abbreviation: "GOR" },
    { name: "Gudu", abbreviation: "GUD" },
    { name: "Illela", abbreviation: "ILL" },
    { name: "Kebbe", abbreviation: "KEB" },
    { name: "Rabah", abbreviation: "RAB" },
    { name: "Sokoto North", abbreviation: "SOK" },
    { name: "Sokoto South", abbreviation: "SOK" },
    { name: "Tambuwal", abbreviation: "TAM" },
    { name: "Wamako", abbreviation: "WAM" },
    { name: "Yabo", abbreviation: "YAB" },
  ],
  Taraba: [
    { name: "Ardo Kola", abbreviation: "ARD" },
    { name: "Bali", abbreviation: "BAL" },
    { name: "Donga", abbreviation: "DON" },
    { name: "Gashaka", abbreviation: "GAS" },
    { name: "Gassol", abbreviation: "GAS" },
    { name: "Ibi", abbreviation: "IBI" },
    { name: "Jalingo", abbreviation: "JAL" },
    { name: "Karim Lamido", abbreviation: "KAR" },
    { name: "Kumi", abbreviation: "KUM" },
    { name: "Lau", abbreviation: "LAU" },
    { name: "Niger", abbreviation: "NIG" },
    { name: "Takum", abbreviation: "TAK" },
    { name: "Ussa", abbreviation: "USS" },
  ],
  Yobe: [
    { name: "Bade", abbreviation: "BAD" },
    { name: "Bursari", abbreviation: "BUR" },
    { name: "Damaturu", abbreviation: "DAM" },
    { name: "Fika", abbreviation: "FIK" },
    { name: "Fune", abbreviation: "FUN" },
    { name: "Geidam", abbreviation: "GEI" },
    { name: "Gujba", abbreviation: "GUJ" },
    { name: "Gulani", abbreviation: "GUL" },
    { name: "Jakusko", abbreviation: "JAK" },
    { name: "Karasuwa", abbreviation: "KAR" },
    { name: "Machina", abbreviation: "MAC" },
    { name: "Nangere", abbreviation: "NAN" },
    { name: "Potiskum", abbreviation: "POT" },
    { name: "Tarmuwa", abbreviation: "TAR" },
    { name: "Yunusari", abbreviation: "YUN" },
    { name: "Yusufari", abbreviation: "YUS" },
  ],
  Zamfara: [
    { name: "Anka", abbreviation: "ANK" },
    { name: "Bakura", abbreviation: "BAK" },
    { name: "Birnin Magaji", abbreviation: "BIR" },
    { name: "Bukkuyum", abbreviation: "BUK" },
    { name: "Chafe", abbreviation: "CHA" },
    { name: "Gummi", abbreviation: "GUM" },
    { name: "Gusau", abbreviation: "GUS" },
    { name: "Kaura Namoda", abbreviation: "KAU" },
    { name: "Maradun", abbreviation: "MAR" },
    { name: "Maru", abbreviation: "MAR" },
    { name: "Shinkafi", abbreviation: "SHI" },
    { name: "Tsafe", abbreviation: "TSA" },
    { name: "Zurmi", abbreviation: "ZUR" },
  ],
};

export type NigerianState = {
  name: string;
  code: string;
};

export const nigerianStates: NigerianState[] = [
  { name: "Abia", code: "Abia" },
  { name: "Adamawa", code: "Adamawa" },
  { name: "Akwa Ibom", code: "AkwaIbom" },
  { name: "Anambra", code: "Anambra" },
  { name: "Bauchi", code: "Bauchi" },
  { name: "Bayelsa", code: "Bayelsa" },
  { name: "Benue", code: "Benue" },
  { name: "Borno", code: "Borno" },
  { name: "Cross River", code: "CrossRiver" },
  { name: "Delta", code: "Delta" },
  { name: "Ebonyi", code: "Ebonyi" },
  { name: "Edo", code: "Edo" },
  { name: "Ekiti", code: "Ekiti" },
  { name: "Enugu", code: "Enugu" },
  { name: "Gombe", code: "Gombe" },
  { name: "Imo", code: "Imo" },
  { name: "Jigawa", code: "Jigawa" },
  { name: "Kaduna", code: "Kaduna" },
  { name: "Kano", code: "Kano" },
  { name: "Katsina", code: "Katsina" },
  { name: "Kebbi", code: "Kebbi" },
  { name: "Kogi", code: "Kogi" },
  { name: "Kwara", code: "Kwara" },
  { name: "Lagos", code: "Lagos" },
  { name: "Nasarawa", code: "Nasarawa" },
  { name: "Niger", code: "Niger" },
  { name: "Ogun", code: "Ogun" },
  { name: "Ondo", code: "Ondo" },
  { name: "Osun", code: "Osun" },
  { name: "Oyo", code: "Oyo" },
  { name: "Plateau", code: "Plateau" },
  { name: "Rivers", code: "Rivers" },
  { name: "Sokoto", code: "Sokoto" },
  { name: "Taraba", code: "Taraba" },
  { name: "Yobe", code: "Yobe" },
  { name: "Zamfara", code: "Zamfara" },
  { name: "FCT", code: "FCT" },
];
